
import { TranslationSet } from './types';

export const APP_NAME = "EcoGuard";

export const TRANSLATIONS: Record<string, TranslationSet> = {
  english: {
    heroTitle: "Report Environmental Issues in Your Language",
    heroSubtitle: "AI-powered, fast, and transparent issue reporting for citizens",
    reportButton: "Report an Issue",
    trackButton: "Track My Complaints",
    formTitle: "Report Environmental Issue",
    languageLabel: "Select Language",
    descriptionLabel: "Describe the Issue",
    descriptionPlaceholder: "Describe what you see (garbage, pollution, etc.)",
    imageLabel: "Upload Image (Optional)",
    locationLabel: "Location",
    detectLocationButton: "Detect My Location",
    manualAddressPlaceholder: "Or enter address manually",
    submitButton: "Submit Complaint",
    successMessage: "Complaint submitted successfully!",
    complaintIdLabel: "Your Complaint ID:",
    trackTitle: "Track Your Complaints",
    searchPlaceholder: "Search by ID or description",
    filterStatus: "Filter by Status",
    filterCategory: "Filter by Category",
    noComplaints: "You haven't reported any issues yet.",
    viewDetails: "View Details",
    rateButton: "Rate",
    statusNew: "New",
    statusInProgress: "In Progress",
    statusResolved: "Resolved",
    loading: "Loading...",
    error: "An error occurred",
    back: "Back",
    close: "Close",
    submit: "Submit",
    feature1Title: "Multi-Language Support",
    feature1Desc: "Report issues easily in English, Hindi, or Telugu.",
    feature2Title: "AI-Powered Routing",
    feature2Desc: "Automatic categorization and routing to correct departments.",
    feature3Title: "Real-Time Tracking",
    feature3Desc: "Watch your complaint move from reported to resolved live.",
    feature4Title: "Quick Reporting",
    feature4Desc: "Submit your environmental concerns in under 2 minutes.",
    dashboardTitle: "Community Health Dashboard",
    dashboardSubtitle: "Real-time environmental monitoring and reporting for your neighborhood.",
    totalReports: "Total Reports",
    activeIssues: "Active Issues",
    resolved: "Resolved",
    recentReports: "Recent Community Reports",
    viewAll: "View All",
    nearbyServices: "Nearby Services",
    recyclingHubs: "Recycling Hubs",
    envAuthorities: "Env. Authorities",
    didYouKnow: "Did you know?",
    learnMoreTips: "Learn More Tips",
    poweredBy: "Powered by Gemini AI",
    aiDesc: "Our platform uses advanced multimodal AI to analyze photos, categorize pollution types, and generate step-by-step action plans.",
    assignTeam: "Assign Team",
    escalateReport: "Escalate Report",
    updateStatus: "Update Status",
    confirmUpdate: "Confirm Status Update",
    currentProgress: "Current Progress",
  },
  hindi: {
    heroTitle: "अपनी भाषा में पर्यावरणीय समस्याएं रिपोर्ट करें",
    heroSubtitle: "AI-संचालित, तेज़ और पारदर्शी समस्या रिपोर्टिंग",
    reportButton: "समस्या रिपोर्ट करें",
    trackButton: "शिकायत ट्रैक करें",
    formTitle: "पर्यावरणीय समस्या रिपोर्ट करें",
    languageLabel: "भाषा चुनें",
    descriptionLabel: "समस्या का वर्णन करें",
    descriptionPlaceholder: "आप क्या देख रहे हैं वर्णन करें (कचरा, प्रदूषण, आदि)",
    imageLabel: "छवि अपलोड करें (वैकल्पिक)",
    locationLabel: "स्थान",
    detectLocationButton: "मेरा स्थान पता करें",
    manualAddressPlaceholder: "या पता मैन्युअल रूप से दर्ज करें",
    submitButton: "शिकायत दर्ज करें",
    successMessage: "शिकायत सफलतापूर्वक दर्ज की गई!",
    complaintIdLabel: "आपकी शिकायत ID:",
    trackTitle: "अपनी शिकायतें ट्रैक करें",
    searchPlaceholder: "ID या विवरण द्वारा खोजें",
    filterStatus: "स्थिति द्वारा फ़िल्टर करें",
    filterCategory: "श्रेणी द्वारा फ़िल्टर करें",
    noComplaints: "आपने अभी तक कोई समस्या रिपोर्ट नहीं की है।",
    viewDetails: "विवरण देखें",
    rateButton: "रेटिंग दें",
    statusNew: "नया",
    statusInProgress: "प्रगति में",
    statusResolved: "हल हो गया",
    loading: "लोड हो रहा है...",
    error: "एक त्रुटि हुई",
    back: "वापस",
    close: "बंद करें",
    submit: "जमा करें",
    feature1Title: "बहु-भाषा समर्थन",
    feature1Desc: "अंग्रेजी, हिंदी या तेलुगु में आसानी से समस्याएं रिपोर्ट करें।",
    feature2Title: "AI-संचालित रूटिंग",
    feature2Desc: "सही विभागों को स्वचालित वर्गीकरण और रूटिंग।",
    feature3Title: "रीयल-टाइम ट्रैकिंग",
    feature3Desc: "अपनी शिकायत को रिपोर्ट से समाधान तक लाइव देखें।",
    feature4Title: "त्वरित रिपोर्टिंग",
    feature4Desc: "2 मिनट से भी कम समय में अपनी चिंताएं दर्ज करें।",
    dashboardTitle: "सामुदायिक स्वास्थ्य डैशबोर्ड",
    dashboardSubtitle: "आपके पड़ोस के लिए रीयल-टाइम पर्यावरण निगरानी और रिपोर्टिंग।",
    totalReports: "कुल रिपोर्ट",
    activeIssues: "सक्रिय मुद्दे",
    resolved: "हल हो गया",
    recentReports: "हालिया सामुदायिक रिपोर्ट",
    viewAll: "सभी देखें",
    nearbyServices: "आस-पास की सेवाएं",
    recyclingHubs: "रीसाइक्लिंग केंद्र",
    envAuthorities: "पर्यावरण प्राधिकरण",
    didYouKnow: "क्या आप जानते हैं?",
    learnMoreTips: "और टिप्स जानें",
    poweredBy: "Gemini AI द्वारा संचालित",
    aiDesc: "हमारा मंच फोटो का विश्लेषण करने और प्रदूषण के प्रकारों को वर्गीकृत करने के लिए उन्नत AI का उपयोग करता है।",
    assignTeam: "टीम असाइन करें",
    escalateReport: "रिपोर्ट एस्केलेट करें",
    updateStatus: "स्थिति अपडेट करें",
    confirmUpdate: "अपडेट की पुष्टि करें",
    currentProgress: "वर्तमान प्रगति",
  },
  telugu: {
    heroTitle: "మీ భాషలో పర్యావరణ సమస్యలను నివేదించండి",
    heroSubtitle: "AI-ఆధారిత, వేగవంతమైన మరియు పారదర్శక సమస్య నివేదన",
    reportButton: "సమస్యను నివేదించండి",
    trackButton: "ఫిర్యాదులను ట్రాక్ చేయండి",
    formTitle: "పర్యావరణ సమస్యను నివేదించండి",
    languageLabel: "భాషను ఎంచుకోండి",
    descriptionLabel: "సమస్యను వివరించండి",
    descriptionPlaceholder: "మీరు చూస్తున్నదాన్ని వివరించండి (చెత్త, కాలుష్యం, మొదలైనవి)",
    imageLabel: "చిత్రాన్ని అప్‌లోడ్ చేయండి (ఐచ్ఛికం)",
    locationLabel: "స్థానం",
    detectLocationButton: "నా స్థానాన్ని గుర్తించండి",
    manualAddressPlaceholder: "లేదా చిరునామాను మానవీయంగా నమోదు చేయండి",
    submitButton: "ఫిర్యాదు సమర్పించండి",
    successMessage: "ఫిర్యాదు విజయవంతంగా సమర్పించబడింది!",
    complaintIdLabel: "మీ ఫిర్యాదు ID:",
    trackTitle: "మీ ఫిర్యాదులను ట్రాక్ చేయండి",
    searchPlaceholder: "ID లేదా వివరణ ద్వారా శోధించండి",
    filterStatus: "స్థితి ద్వారా ఫిల్టర్ చేయండి",
    filterCategory: "వర్గం ద్వారా ఫిల్టర్ చేయండి",
    noComplaints: "మీరు ఇంకా ఏ సమస్యను నివేదించలేదు।",
    viewDetails: "వివరాలను చూడండి",
    rateButton: "రేటింగ్ ఇవ్వండి",
    statusNew: "కొత్త",
    statusInProgress: "ప్రగతిలో ఉంది",
    statusResolved: "పరిష్కరించబడింది",
    loading: "లోడ్ అవుతోంది...",
    error: "లోపం సంభవించింది",
    back: "వెనక్కి",
    close: "మూసివేయండి",
    submit: "సమర్పించండి",
    feature1Title: "బహుభాషా మద్దతు",
    feature1Desc: "ఇంగ్లీష్, హిందీ లేదా తెలుగులో సులభంగా నివేదించండి.",
    feature2Title: "AI-ఆధారిత రూటింగ్",
    feature2Desc: "సరైన విభాగాలకు ఆటోమేటిక్ వర్గీకరణ మరియు రూటింగ్.",
    feature3Title: "రియల్ టైమ్ ట్రాకింగ్",
    feature3Desc: "పరిష్కారం వరకు మీ ఫిర్యాదు పురోగతిని చూడండి.",
    feature4Title: "వేగవంతమైన నివేదన",
    feature4Desc: "2 నిమిషాలలోపు మీ ఫిర్యాదులను సమర్పించండి.",
    dashboardTitle: "కమ్యూనిటీ హెల్త్ డాష్‌బోర్డ్",
    dashboardSubtitle: "మీ పరిసరాల కోసం రియల్ టైమ్ పర్యావరణ పర్యవేక్షణ మరియు నివేదిక.",
    totalReports: "మొత్తం నివేదికలు",
    activeIssues: "యాక్టివ్ సమస్యలు",
    resolved: "పరిష్కరించబడింది",
    recentReports: "ఇటీవలి కమ్యూనిటీ నివేదికలు",
    viewAll: "అన్నీ చూడండి",
    nearbyServices: "దగ్గరి సేవలు",
    recyclingHubs: "రీసైక్లింగ్ కేంద్రాలు",
    envAuthorities: "పర్యావరణ అధికారులు",
    didYouKnow: "మీకు తెలుసా?",
    learnMoreTips: "మరిన్ని చిట్కాలు తెలుసుకోండి",
    poweredBy: "Gemini AI ద్వారా ఆధారితం",
    aiDesc: "ఫోటోలను విశ్లేషించడానికి మరియు కాలుష్య రకాలను వర్గీకరించడానికి మా ప్లాట్‌ఫారమ్ అధునాతన AIని ఉపయోగిస్తుంది.",
    assignTeam: "బృందాన్ని కేటాయించండి",
    escalateReport: "నివేదికను ఎస్కలేట్ చేయండి",
    updateStatus: "స్థ స్థితిని నవీకరించండి",
    confirmUpdate: "నవీకరణను నిర్ధారించండి",
    currentProgress: "ప్రస్తుత పురోగతి",
  }
};

export const DEPARTMENTS = [
  "Sanitation Department (GHMC)",
  "Pollution Control Board (TPCB)",
  "Water Board (HMWS&SB)",
  "Municipal Corporation",
  "Forest & Wildlife Dept"
];

export const CATEGORIES = [
  "Solid Waste Management",
  "Water Pollution",
  "Air Quality Issues",
  "Sewage Leakage",
  "Illegal Dumping",
  "Tree Cutting",
  "Noise Pollution"
];
